name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        #TODO macos impl
        #os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      if: runner.os != 'Windows'
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi
    - name: Install Rust Windows
      if: runner.os == 'Windows'
      run: |
        if (Get-Command "rustup" -ErrorAction SilentlyContinue) {
            rustup update
        } else {
            Invoke-WebRequest https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
            ./rustup-init.exe -y --profile minimal --default-toolchain stable
            echo ::add-path::%USERPROFILE%\.cargo\bin
        }
    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Install Valgrind
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y valgrind

    - name: Gather system info Windows
      if: runner.os == 'Windows'
      run: |
        ipconfig

    - name: Gather system info Linux
      if: runner.os == 'Linux'
      run: |
        ifconfig

    - name: Gather system info MacOS
      if: runner.os == 'macOS'
      run: |
        ifconfig

    - name: Test
      if: runner.os != 'Linux'
      run: cargo test -- --nocapture

    - name: Valgrind Test
      if: runner.os == 'Linux'
      env:
        CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: "valgrind --leak-check=full"
      run: cargo test -- --nocapture
